version: "3.9"

services:
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run dev"
